import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { text: "uploading photography" },
    { text: "making new art..." },
    { text: "uploading art backlog" },
    { text: "updating links page, so many good sites!" }
];
const ListRow2_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow3_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["style-li-11"],
    ["style-link-8"],
    ["style-hr-3"],
    ["style-heading-21"]
];
const ListRow2_meta: string[][] = [
    ["style-image-12", "style-br-4"],
    ["style-button", "style-air-3-7-2026-6-34-12"],
    ["n75", "style-heading-10"]
];
const ListRow3_meta: string[][] = [
    ["style-figure", "style-image-7"],
    ["style-figcaption", "style-link-16"],
    ["n91", "style-ul-11"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <section className="h-full block">
              <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                Last updated: 06 september 2026
              </h3>
              {" "}
              <p className="block mb-4" data-ditto-id="style-p-2">
                {" HOI! Welcome to the Myrtletribe "}
                <img className="w-5 h-5 inline max-w-full overflow-clip" data-ditto-id="style-image-3" data-component="image" alt="myrtletribe: small pixel girl with green hair" src="/assets/cloned/images/94852669a3f4.png" />
                {" I'm a hobby artist and study evolutionary ecology. Here you can find my art, book reviews and blog posts. "}
              </p>
              {" "}
              <div className="flex justify-between gap-8 max-lg:flex-col" data-ditto-id="style-aside">
                <div className="block" data-ditto-id="style-navbar-2">
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-nav" data-component="heading">
                    What's new?
                  </h3>
                  {" "}
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-ditto-id="style-heading-15">
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-component="heading">
                      Blog post
                    </h4>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-p-6">
                      <time className="inline" data-ditto-id="style-link-4">
                        30/06/2026
                      </time>
                      {": "}
                      <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-16" data-component="link" href="/library/blog">
                        Lemon and Raisin Cake
                      </a>
                    </p>
                    {" "}
                  </article>
                  {" "}
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-ditto-id="style-ul">
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-ditto-id="style-li-9" data-component="heading">
                      Book review
                    </h4>
                    {" "}
                    <p className="block mb-[0.9rem]" data-ditto-id="style-link-5">
                      <time className="inline" data-ditto-id="style-li-3">
                        23/05/2026
                      </time>
                      {": "}
                      <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-6" data-component="link" href="/library/reading-log">
                        Psyche (L. Couperus, 1898)
                      </a>
                      {" "}
                    </p>
                    {" "}
                  </article>
                  {" "}
                  <article className="block mb-4" data-ditto-id="style-hr">
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-9" data-component="heading">
                      Artwork
                    </h4>
                    {" "}
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-2" data-component="link" href="/gallery/artwork">
                      {" "}
                      <img className="w-73 h-75 border-[5px] border-solid border-surface-2 inline max-w-full max-h-75 rounded-[3px] overflow-clip shadow-[var(--clr-1)_4px_5px_2px_0px] max-md:w-[7.5625rem] max-md:h-31" data-component="image" alt="artwork page" src="/assets/cloned/images/1d95a4975f71.jpg" />
                    </a>
                    {" "}
                  </article>
                  {" "}
                </div>
                {" "}
                <div className="block" data-ditto-id="style-heading">
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5">
                    <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-2" data-component="heading">
                      Currently reading
                    </h3>
                    {" "}
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-ditto-id="style-ul-12" data-component="heading">
                      {"Flowers for Algernon (D. Keyes, 1959) "}
                    </h4>
                    {" "}
                    <figure className="block mb-[0.9rem]" data-ditto-id="style-li">
                      <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-2" data-component="link" href="https://app.thestorygraph.com/profile/myrtletribe" target="_blank">
                        <img className="w-26 h-40 inline max-w-full max-h-40 mt-[0.3125rem] rounded-xs overflow-clip shadow-[var(--clr-2)_1px_2px_2px_0px]" data-ditto-id="style-heading-17" data-component="image" alt="storygraph profile" src="/assets/cloned/images/57b1cc3ec2ce.png" />
                      </a>
                      {" "}
                    </figure>
                    {" "}
                  </article>
                  {" "}
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-ditto-id="style-ul-3">
                    <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-li-10" data-component="heading">
                      Currently working on...
                    </h3>
                    {" "}
                    <ul className="w-full border border-dotted border-primary block mt-5 mb-7.5 p-2 text-[0.8125rem] italic leading-[1.625rem] [list-style-type:none] list-outside bg-surface-2 shadow-[var(--clr-2)_2px_2px_2px_0px] md:max-lg:w-[90%]" data-ditto-id="style-link-7">
                      {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                    </ul>
                    {" "}
                  </article>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="block -mb-px p-2.5 bg-clr-3" data-ditto-id="style-ul-4">
                <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-ditto-id="style-link-29">
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-p" data-component="heading">
                    Contact
                  </h3>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-hr-5">
                    <span className="inline [overflow-wrap:anywhere]" data-ditto-id="style-heading-3">
                      <strong className="inline font-bold">
                        myrtletribe@protonmail.com
                      </strong>
                    </span>
                  </p>
                  {" "}
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-li-2" data-component="heading">
                    Buttons
                  </h3>
                  {" "}
                  <p className="block mb-[0.9rem]" data-ditto-id="style-hr-4">
                    <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-ditto-id="style-heading-7" data-component="image" alt="88x31 button" src="/assets/cloned/images/429ec6d8c493.png" />
                    {" "}
                    <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-ditto-id="style-ul-5" data-component="image" alt="88x31 button" src="/assets/cloned/images/de4b688cf70b.png" />
                    <br className="inline" data-ditto-id="style-li-12" />
                    {" "}
                    <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4" data-ditto-id="style-link-9">
                      Please no hotlink
                    </span>
                    {" "}
                  </p>
                  {" "}
                </article>
                {" "}
              </div>
              {" "}
              <img className="w-10 h-16 inline max-w-full overflow-clip" data-ditto-id="style-li-13" data-component="image" alt="" src="/assets/cloned/images/e59643e0d2aa.gif" />
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-ditto-id="style-link-10">
            <div className="block" data-ditto-id="style-image-9" id="navbar">
              <nav className="block" data-ditto-id="style-center" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-span-4" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-footer-2" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-footer">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-4" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-br-5" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-11">
                  <li className="list-item" data-ditto-id="style-link">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-2" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-image-5">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-br-2" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-div" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-3">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-link-30" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-p-4" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-button-2">
                  <li className="list-item" data-ditto-id="style-june-2-7-2026-16-20-47">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-19" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-span-2">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-31" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-button-3" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-heading-8">
                  {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-12" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-p-5">
                  <li className="list-item" data-ditto-id="style-span">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-17" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-image">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-18" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-image-2" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-ditto-id="style-aside-2">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-navbar">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" data-ditto-id="style-nav-2" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-heading-20">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-ditto-id="style-hr-6" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-ditto-id="style-p-11" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-19" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-18" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-ul-6" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-ditto-id="style-li-4" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-ditto-id="style-link-20" />
            {"Last updated: "}
            <span className="inline" data-ditto-id="style-li-5" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-ditto-id="style-link-21">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-7" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-ditto-id="style-heading-11" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
