import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import { LAST_UPDATED } from "../../last-updated.generated";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "https://github.com/godly-raam", text: "Automated AD Cyber Range & Attack Path Analysis" },
    { href: "https://github.com/godly-raam", text: "Custom Red Team C2 Framework" },
    { href: "https://github.com/godly-raam", text: "CVE Research & Exploit Development Portfolio" }
];
const ListRow2_data = [
    { href: "/library/reading-log", label: "Anime Log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Mental Notes" }
];
const ListRow3_data = [
    { href: "/info/about/", label: "About" }
];
const ListRow_cids: string[][] = [
    ["n38"],
    ["n39"],
    ["n40"],
    ["n41"]
];
const ListRow2_cids: string[][] = [
    ["n71", "n72"],
    ["n73", "n74"],
    ["n75", "n76"]
];
const ListRow3_cids: string[][] = [
    ["n87", "n88"],
    ["n89", "n90"],
    ["n91", "n92"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4" data-cid="n1">
        <div className="block" data-cid="n2" id="header">
          <header className="block my-5 text-center" data-cid="n3">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-cid="n4" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between" data-cid="n5">
          <main className="border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0" data-cid="n6">
            <section className="h-full block" data-cid="n7">
              <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n8" data-component="heading">
                Last updated: {LAST_UPDATED}
              </h3>
              {" "}
              <p className="block mb-4" data-cid="n9">
                {" HOI! Welcome to the Crib "}
                <img className="w-5 h-5 inline max-w-full overflow-clip" data-cid="n10" data-component="image" alt="myrtletribe: small pixel girl with green hair" src="/assets/cloned/images/94852669a3f4.png" />
                {" I'm a hekkor man and watch a lot of anime. Here you can find my projects, anime reviews and blog posts. "}
              </p>
              {" "}
              <div className="flex justify-between gap-8 max-lg:flex-col" data-cid="n11">
                <div className="block" data-cid="n12">
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n13" data-component="heading">
                    What's new?
                  </h3>
                  {" "}
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-cid="n14">
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-cid="n15" data-component="heading">
                      Blog post
                    </h4>
                    {" "}
                    <p className="block mb-[0.9rem]" data-cid="n16">
                      <time className="inline" data-cid="n17">
                        30/06/2026
                      </time>
                      {": "}
                      <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n18" data-component="link" href="/library/blog">
                        Lemon and Raisin Cake
                      </a>
                    </p>
                    {" "}
                  </article>
                  {" "}
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-cid="n19">
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-cid="n20" data-component="heading">
                      Book review
                    </h4>
                    {" "}
                    <p className="block mb-[0.9rem]" data-cid="n21">
                      <time className="inline" data-cid="n22">
                        23/05/2026
                      </time>
                      {": "}
                      <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n23" data-component="link" href="/library/reading-log">
                        Psyche (L. Couperus, 1898)
                      </a>
                      {" "}
                    </p>
                    {" "}
                  </article>
                  {" "}
                  <article className="block mb-4" data-cid="n24">
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-cid="n25" data-component="heading">
                      Artwork
                    </h4>
                    {" "}
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n26" data-component="link" href="/artwork">
                      {" "}
                      <img className="w-73 h-75 border-[5px] border-solid border-surface-2 inline max-w-full max-h-75 rounded-[3px] overflow-clip shadow-[var(--clr-1)_4px_5px_2px_0px] max-md:w-[7.5625rem] max-md:h-31" data-cid="n27" data-component="image" alt="artwork page" src="/assets/cloned/images/1d95a4975f71.jpg" />
                    </a>
                    {" "}
                  </article>
                  {" "}
                </div>
                {" "}
                <div className="block" data-cid="n28">
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-cid="n29">
                    <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n30" data-component="heading">
                      Currently watching
                    </h3>
                    {" "}
                    <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-cid="n31" data-component="heading">
                      {"That Time I Got Reincarnated as a Slime"}
                    </h4>
                    {" "}
                    <figure className="block mb-[0.9rem]" data-cid="n32">
                      <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n33" data-component="link" href="https://myanimelist.net/anime/37430/Tensei_Shitara_Slime_Datta_Ken" target="_blank">
                        <img className="w-26 h-40 inline max-w-full max-h-40 mt-[0.3125rem] rounded-xs overflow-clip shadow-[var(--clr-2)_1px_2px_2px_0px]" data-cid="n34" data-component="image" alt="That Time I Got Reincarnated as a Slime cover" src="https://cdn.myanimelist.net/images/anime/1069/123309.jpg" />
                      </a>
                      {" "}
                    </figure>
                    {" "}
                  </article>
                  {" "}
                  <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-cid="n35">
                    <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n36" data-component="heading">
                      Projects
                    </h3>
                    {" "}
                    <ul className="w-full border border-dotted border-primary block mt-5 mb-7.5 p-2 text-[0.8125rem] italic leading-[1.625rem] [list-style-type:none] list-outside bg-surface-2 shadow-[var(--clr-2)_2px_2px_2px_0px] md:max-lg:w-[90%]" data-cid="n37">
                      {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                    </ul>
                    {" "}
                  </article>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="block -mb-px p-2.5 bg-clr-3" data-cid="n42">
                <article className="w-full max-w-100 block mb-[0.9rem] rounded-xs text-sm leading-4.5" data-cid="n43">
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n44" data-component="heading">
                    Contact
                  </h3>
                  {" "}
                  <p className="block mb-[0.9rem]" data-cid="n45">
                    <span className="inline [overflow-wrap:anywhere]" data-cid="n46">
                      <strong className="inline font-bold" data-cid="n47">
                        rambabu.ksingh2005@gmail.com
                      </strong>
                    </span>
                  </p>
                  {" "}
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n48" data-component="heading">
                    Buttons
                  </h3>
                  {" "}
                  <p className="block mb-[0.9rem]" data-cid="n49">
                    <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-cid="n50" data-component="image" alt="88x31 button" src="/assets/cloned/images/429ec6d8c493.png" />
                    {" "}
                    <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-cid="n51" data-component="image" alt="88x31 button" src="/assets/cloned/images/de4b688cf70b.png" />
                    <br className="inline" data-cid="n52" />
                    {" "}
                    <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4" data-cid="n53">
                      Please no hotlink
                    </span>
                    {" "}
                  </p>
                  {" "}
                </article>
                {" "}
              </div>
              {" "}
              <img className="w-10 h-16 inline max-w-full overflow-clip" data-cid="n54" data-component="image" alt="" src="/assets/cloned/images/e59643e0d2aa.gif" />
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-cid="n55">
            <div className="block" data-cid="n56" id="navbar">
              <nav className="block" data-cid="n57" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-cid="n58" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n59" />
                {" "}
                <p className="block mb-4" data-cid="n60">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n61" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n68" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n69" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n70">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n77" />
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n84" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n85" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n86">
                  {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n93" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n94" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n95">
                  <li className="list-item" data-cid="n96">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n97" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-cid="n100" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-cid="n101">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-cid="n102">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" data-cid="n103" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-cid="n104">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-cid="n105" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-cid="n106" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n107" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n108" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n109" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-cid="n110" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-cid="n111" />
            {"Last updated: "}
            <span className="inline" data-cid="n112" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-cid="n113">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n114" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-cid="n115" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
