import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow2_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["style-heading-11", "style-ul-7"],
    ["n117", "style-p-3"],
    ["style-link-32", "style-heading-4"]
];
const ListRow2_meta: string[][] = [
    ["style-heading-13", "style-ul-9"],
    ["style-link-33", "style-link-24"],
    ["style-link-34", "style-link-25"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="w-full border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <section className="h-full block">
              <img className="w-7 h-[2.4375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/b145f4e51144.gif" />
              {" "}
              <p className="block mb-4" data-ditto-id="style-p-2">
                Thank you for stopping by!
              </p>
              {" "}
              <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-image-3">
                <li className="list-item before:content-['❧_'] before:inline-block before:w-[0.6625rem] before:h-[1.1rem] before:mr-1.5 before:text-foreground before:text-lg before:leading-[1.125rem]" data-ditto-id="style-aside">
                  {"Messages left here: "}
                  <span className="inline" data-ditto-id="style-navbar-2" id="entry-count">
                    93
                  </span>
                  {" "}
                </li>
              </ul>
              {" "}
              <div className="block overflow-auto text-color-002 [background-attachment:fixed]" style={{ backgroundImage: "url(\"\")" }} data-ditto-id="style-nav" id="c_widget">
                <div className="block p-2.5 rounded-xs lowercase bg-surface-3" data-ditto-id="style-heading-15" id="c_inputDiv">
                  <form className="block" id="c_form" target="c_hiddenIframe">
                    <h2 className="block text-color-003 text-2xl italic leading-[2.125rem]" data-ditto-id="style-p-6" data-component="heading" id="c_widgetTitle">
                      Leave a message
                    </h2>
                    {" "}
                    <div className="block my-[0.3125rem]" data-ditto-id="style-link-4" id="c_nameWrapper">
                      <label className="inline cursor-default" data-ditto-id="style-heading-16" htmlFor="entry.1260003527">
                        Name
                      </label>
                      {" "}
                      <input className="w-40 h-[1.5625rem] border border-dotted border-color-004 inline-block p-1 rounded-[5px] overflow-clip [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] normal-case bg-surface cursor-text" data-ditto-id="style-ul" data-component="input" id="entry.1260003527" name="entry.1260003527" type="text" />
                      {" "}
                    </div>
                    {" "}
                    <div className="block my-[0.3125rem]" data-ditto-id="style-li-9" id="c_websiteWrapper">
                      <label className="inline cursor-default" data-ditto-id="style-link-5" htmlFor="entry.908867855">
                        Website (Optional)
                      </label>
                      {" "}
                      <input className="w-40 h-[1.5625rem] border border-dotted border-color-004 inline-block p-1 rounded-[5px] overflow-clip [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] normal-case bg-surface cursor-text" data-ditto-id="style-li-3" data-component="input" id="entry.908867855" name="entry.908867855" pattern="https://.*" type="url" />
                      {" "}
                    </div>
                    {" "}
                    <div className="block my-[0.3125rem]" data-ditto-id="style-link-6" id="c_textWrapper">
                      <label className="inline cursor-default" data-ditto-id="style-hr" htmlFor="entry.1243546763" />
                      {" "}
                      <textarea className="w-199 h-17.5 border border-dotted border-color-004 inline-block max-w-225 p-1 rounded-[5px] overflow-auto [font-family:monospace] text-[0.8125rem] leading-[0.9375rem] normal-case whitespace-pre-wrap [overflow-wrap:break-word] bg-surface cursor-text max-md:w-37.5 md:max-lg:w-116" data-ditto-id="style-heading-9" data-component="textarea" id="entry.1243546763" name="entry.1243546763" />
                      {" "}
                    </div>
                    {" "}
                    <input className="w-[3.0625rem] h-[1.5625rem] border border-solid border-surface block p-1 rounded-[5px] overflow-clip text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center whitespace-pre text-nowrap bg-surface cursor-default" data-ditto-id="style-ul-2" data-component="button" id="c_submitButton" name="c_submitButton" type="submit" value="Submit" />
                    {" "}
                  </form>
                  {" "}
                </div>
                {" "}
                <div className="block mt-2.5" id="c_container">
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-heading" id="X|--|7-9-2026 19:19:43">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                      X
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-heading-2">
                      7/9/2026
                    </span>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-ul-12">
                      {"Keep up the great work "}
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-li" data-component="button" value="X|--|7-9-2026 19:19:43">
                      Reply
                    </button>
                    <button className="border border-solid border-surface block float-right mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-hr-2" data-component="button">
                      Show Replies (1)
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-heading-17" id="tez0|--|23-8-2026 19:31:29">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-ul-3" data-component="heading">
                      tez0
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-li-10">
                      23/8/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-7" data-component="link" href="https://tez0.neocities.org/">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-li-11">
                      hey again Myrtle, went back on your website after a couple months to see what you're up to. still love the book reviews and whimsy of your page, I hope you feel better than at the beginning of this month. take care, you deserve it :)
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-link-8" data-component="button" value="tez0|--|23-8-2026 19:31:29">
                      Reply
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-hr-3" id="maccadot|--|22-8-2026 17:19:32">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-21" data-component="heading">
                      maccadot
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-ul-4">
                      22/8/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-29" data-component="link" href="https://maccadot.neocities.org/">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-p">
                      i ADORE how you've crafted this space :) i think the minimalist theme really lets your art and reviews shine (and boy do they). added ur button to my space!
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-hr-5" data-component="button" value="maccadot|--|22-8-2026 17:19:32">
                      Reply
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-heading-3" id="leaferreefer|--|15-8-2026 6:35:45">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                      leaferreefer
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-li-2">
                      15/8/2026
                    </span>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-hr-4">
                      ye its gud, but like. how does the art look like smooth as butter? oh my science i want to be that good!
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-heading-7" data-component="button" value="leaferreefer|--|15-8-2026 6:35:45">
                      Reply
                    </button>
                    <button className="border border-solid border-surface block float-right mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-ul-5" data-component="button">
                      Show Replies (1)
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-li-12" id="Prism|--|9-8-2026 6:58:46">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-9" data-component="heading">
                      Prism
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-li-13">
                      9/8/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-10" data-component="link" href="https://entropyprism.neocities.org/home">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-image-9">
                      I love the vibes of this place, and I hope your ecology studies are going well!
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-center" data-component="button" value="Prism|--|9-8-2026 6:58:46">
                      Reply
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-span-4" id="Karisan|--|19-7-2026 1:23:16">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-footer-2" data-component="heading">
                      Karisan
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-footer">
                      19/7/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-4" data-component="link" href="https://uncannydream.neocities.org/">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-br-5">
                      your website is magical — I wandered in and immediately got sparkles in my eyes. I added your button to my place so maybe we can be little web‑neighbors in this strange glowing realm.
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-link-11" data-component="button" value="Karisan|--|19-7-2026 1:23:16">
                      Reply
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-link" id="ari|--|4-7-2026 16:32:56">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-2" data-component="heading">
                      ari
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-image-5">
                      4/7/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-br-2" data-component="link" href="https://ari.lt/">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify">
                      going home after a trip and decided to finally reply to ur guestbook comment
                      <br className="inline" data-ditto-id="style-div" />
                      <br className="inline" data-ditto-id="style-link-3" />
                      i wanted to wish u best of luck in norway, its really awesome ur working in ecology stuff 🤎
                      <br className="inline" data-ditto-id="style-image-12" />
                      <br className="inline" data-ditto-id="style-br-4" />
                      p.s. hope migrating from winbowse to linux goes well ^-^
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-button" data-component="button" value="ari|--|4-7-2026 16:32:56">
                      Reply
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-air-3-7-2026-6-34-12" id="air |--|3-7-2026 6:34:12">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                      {"air "}
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-heading-10">
                      3/7/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-30" data-component="link" href="https://4cornersofpluto.neocities.org/blog">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify" data-ditto-id="style-p-4">
                      wishing you luck with landing a project in norway! and let us know how moving from windows to linux goes.. i nearly pulled the trigger the other day because i had to reinstall windows just to make file explorer work -_-' love the new site layout btw!
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-button-2" data-component="button" value="air |--|3-7-2026 6:34:12">
                      Reply
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-june-2-7-2026-16-20-47" id="june|--|2-7-2026 16:20:47">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-19" data-component="heading">
                      june
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-span-2">
                      2/7/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-31" data-component="link" href="https://koi.rip/">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify">
                      hiii i came here from arivertisements i love your siteeee :3
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-button-3" data-component="button" value="june|--|2-7-2026 16:20:47">
                      Reply
                    </button>
                    <button className="border border-solid border-surface block float-right mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-heading-8" data-component="button">
                      Show Replies (1)
                    </button>
                  </div>
                  <div className="block my-2.5 p-2.5 rounded-xs bg-surface-3" data-ditto-id="style-figure" id="LadyAye7|--|2-7-2026 12:52:35">
                    <h3 className="inline-block mr-2.5 text-color-001 [font-family:serif] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-image-7" data-component="heading">
                      LadyAye7
                    </h3>
                    <span className="block float-right opacity-60" data-ditto-id="style-figcaption">
                      2/7/2026
                    </span>
                    <a className="inline text-color-006 lowercase underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-16" data-component="link" href="https://aye7grimoire.neocities.org/">
                      Website
                    </a>
                    <p className="block mt-2.5 text-justify">
                      Greetings from LadyAye7. I'm just out here roaming Neocities like a little constellation, visiting the worlds people build here.
                      <br className="inline" data-ditto-id="style-ul-11" />
                      {"I’m on my own journey of learning the craft — coding, HTML, all the tiny pieces that make a site feel alive. I have been inspired, so for that, thank you! <3<3<3 "}
                      <br className="inline" />
                      Your page caught my eye, so I wanted to leave a small trace of my visit.
                    </p>
                    <button className="border border-solid border-surface inline-block mt-2.5 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center lowercase bg-surface cursor-default" data-ditto-id="style-link-12" data-component="button" value="LadyAye7|--|2-7-2026 12:52:35">
                      Reply
                    </button>
                  </div>
                  <div className="block text-center" data-ditto-id="style-p-5" id="c_pagination">
                    <button className="border border-solid border-surface inline-block opacity-60 mx-1 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] lowercase bg-surface cursor-default" data-ditto-id="style-span" data-component="button" disabled id="c_leftButton" name="left">
                      {"<<"}
                    </button>
                    <button className="border border-solid border-surface inline-block mx-1 p-1 rounded-[5px] text-color-003 [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] lowercase bg-surface cursor-default" data-ditto-id="style-link-17" data-component="button" id="c_rightButton" name="right">
                      {">>"}
                    </button>
                  </div>
                </div>
                {" "}
              </div>
              {" Uses "}
              <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image" data-component="link" href="https://virtualobserver.moe/ayano/comment-widget">
                Virtual Observer's comment widget
              </a>
              {". Thank you! "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-ditto-id="style-link-18">
            <div className="block" data-ditto-id="style-image-2" id="navbar">
              <nav className="block" data-ditto-id="style-aside-2" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-navbar" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-nav-2" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-heading-20">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-hr-6" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-p-11" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-19">
                  <li className="list-item" data-ditto-id="style-heading-18">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-6" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-li-4">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-20" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-li-5" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-21" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-hr-7">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-5" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-hr-8">
                  <li className="list-item" data-ditto-id="style-heading-12">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-8" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-22" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-li-6" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-23" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-hr-9">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-10" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-6" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-hr-11">
                  <li className="list-item" data-ditto-id="style-heading-14">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-10" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-li-7">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-26" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-li-8" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-ditto-id="style-link-27">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-image-8">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-span-3">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-ditto-id="style-footer-3" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-6" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-br" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-28" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-ditto-id="style-link-13" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-ditto-id="style-link-14" />
            {"Last updated: "}
            <span className="inline" data-ditto-id="style-image-10" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-ditto-id="style-br-3">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-lastupdate" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
