import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "https://caminus.quest/uglass", label: "Uranium Glass", text: " by\n                            Caminus" },
    { href: "https://clearglass.neocities.org/shrines/umineko", label: "Umineko", text: " by Clearglass" },
    { href: "https://howsoonisnow.org/shrines/seasonalproduce/", label: "Seasonal Produce", text: " by How Soon Is Now?" },
    { href: "https://sadgrlonline.github.io/archived-sadgrl.online/shrines/tatu/", label: "t.A.T.u.", text: " by Sadgrl.online" }
];
const ListRow2_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow3_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["n75", "style-heading-10"],
    ["style-link-30", "style-p-4"],
    ["style-button-2", "style-june-2-7-2026-16-20-47"],
    ["style-heading-19", "style-span-2"]
];
const ListRow2_meta: string[][] = [
    ["n194", "style-details"],
    ["n196", "style-p-7"],
    ["n198", "style-p-8"]
];
const ListRow3_meta: string[][] = [
    ["n210", "style-summary"],
    ["n212", "style-p-9"],
    ["n214", "style-p-10"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <section className="h-full block text-center">
              <h3 className="block max-w-175 mx-auto text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                Personal sites
              </h3>
              {" "}
              <div className="block max-w-125 mt-2 mb-4 mx-auto" data-ditto-id="style-p-2">
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-3" data-component="link" href="https://alienheadshitkid.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-aside" data-component="image" alt="alienheadshitkid" src="/assets/cloned/images/883ac66b2267.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-navbar-2" data-component="link" href="https://angelsaremathematical.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-nav" data-component="image" alt="angelsaremathematical" src="/assets/cloned/images/416bbea47a5a.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-15" data-component="link" href="https://forestfolke.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-component="image" alt="forestfolke" src="/assets/cloned/images/f29e279a1418.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-p-6" data-component="link" href="https://zonaplankton.net/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-4" data-component="image" alt="zonaplankton" src="/assets/cloned/images/90f911cacf00.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-16" data-component="link" href="https://ruralrose.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-ul" data-component="image" alt="ruralrose" src="/assets/cloned/images/95957bd7d8c5.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-9" data-component="link" href="https://meyyebs.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-5" data-component="image" alt="sticky hands" src="/assets/cloned/images/fd460d612255.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-3" data-component="link" href="https://sunpurr.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-6" data-component="image" alt="sunpurr" src="/assets/cloned/images/e438741caf4a.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-hr" data-component="link" href="https://sweetfish.site/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-heading-9" data-component="image" alt="sweetfish" src="/assets/cloned/images/b8e19ca1eb0c.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-2" data-component="link" href="https://moocyte.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-component="image" alt="moocyte" src="/assets/cloned/images/687c8c4b7357.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading" data-component="link" href="https://skep.place/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-component="image" alt="skep's place" src="/assets/cloned/images/3398d4a51928.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-2" data-component="link" href="https://bisha.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-ul-12" data-component="image" alt="bisha" src="/assets/cloned/images/a42c81224bbd.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li" data-component="link" href="https://everythingkris.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-hr-2" data-component="image" alt="everythingkris!" src="/assets/cloned/images/e31281997f9f.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-17" data-component="link" href="https://oopsiedoodle.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-ul-3" data-component="image" alt="oopsiedoodle" src="/assets/cloned/images/75519bbe5279.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-10" data-component="link" href="https://bondiaries.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-7" data-component="image" alt="bondiaries" src="/assets/cloned/images/f1ff64c07dde.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-11" data-component="link" href="https://snails.town/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-8" data-component="image" alt="snails" src="/assets/cloned/images/bcb3c811ce01.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-hr-3" data-component="link" href="https://onio.club/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-heading-21" data-component="image" alt="onio" src="/assets/cloned/images/e789978964e8.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-4" data-component="link" href="https://win1999.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-29" data-component="image" alt="win1999" src="/assets/cloned/images/a2e4e7bf1f84.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-p" data-component="link" href="https://ari.lt/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-hr-5" data-component="image" alt="ari" src="/assets/cloned/images/53d3c8cf829f.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-3" data-component="link" href="https://ribo.zone/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-component="image" alt="ribozone" src="/assets/cloned/images/53e3e886794f.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-2" data-component="link" href="https://howsoonisnow.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-hr-4" data-component="image" alt="howsoonisnow?" src="/assets/cloned/images/cd0d0c5a86a5.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-7" data-component="link" href="https://mermaidgrey.neocities.org/" target="_blank">
                  <div className="h-[1.9375rem] border border-outset border-color-004 inline-block m-0.5 p-1 rounded-xs align-top [font-family:'Source_Code_Pro'] text-[0.6875rem] leading-3.5 bg-accent cursor-default" data-ditto-id="style-ul-5" data-component="button">
                    Mermaidgrey
                  </div>
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-12" data-component="link" href="https://mabevillage.neocities.org/" target="_blank">
                  <div className="h-[1.9375rem] border border-outset border-color-004 inline-block m-0.5 p-1 rounded-xs align-top [font-family:'Source_Code_Pro'] text-[0.6875rem] leading-3.5 bg-accent cursor-default" data-ditto-id="style-link-9" data-component="button" alt="mabevillage">
                    Mabevillage
                  </div>
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-13" data-component="link" href="https://masonarmand.com/" target="_blank">
                  <div className="h-[1.9375rem] border border-outset border-color-004 inline-block m-0.5 p-1 rounded-xs align-top [font-family:'Source_Code_Pro'] text-[0.6875rem] leading-3.5 bg-accent cursor-default" data-ditto-id="style-link-10" data-component="button" alt="masonarmand">
                    Mason Armand
                  </div>
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-9" data-component="link" href="https://waxwing.neocities.org/" target="_blank">
                  <div className="h-[1.9375rem] border border-outset border-color-004 inline-block m-0.5 p-1 rounded-xs align-top [font-family:'Source_Code_Pro'] text-[0.6875rem] leading-3.5 bg-accent cursor-default" data-ditto-id="style-center" data-component="button">
                    Waxwing
                  </div>
                </a>
                {" "}
              </div>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-span-4">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:text-center" data-ditto-id="style-footer-2">
                  {"View all sites I follow via Neocities "}
                  <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-footer" data-component="link" href="https://neocities.org/site/myrtletribe/follows" target="_blank">
                    here
                  </a>
                  !
                </span>
                {" "}
              </p>
              {" "}
              <center className="block [text-align:-webkit-center]" data-ditto-id="style-image-4">
                <div className="w-180.5 h-24.5 inline-block relative max-w-full overflow-hidden max-md:w-[9.0625rem] md:max-lg:w-123.5" data-ditto-id="style-br-5" target="_blank" title="An advertisement showing a silly image and author information.">
                  <div className="box-content h-full table overflow-hidden text-surface [font-family:monospace] text-[0.8125rem] leading-[0.9375rem] text-center bg-clr-7" data-ditto-id="style-link-11">
                    <div className="box-content table-cell relative align-middle" data-ditto-id="style-link">
                      <div className="box-content inline-block" data-ditto-id="style-link-2">
                        <a className="box-content inline underline cursor-pointer after:content-[''] after:block after:absolute after:inset-0 after:z-1 after:w-180.5 after:h-24.5 max-md:after:w-[9.0625rem] md:max-lg:after:w-123.5" data-ditto-id="style-image-5" data-component="link" href="https://wiby.me/surprise/" rel="noopener noreferrer">
                          <img className="box-content w-180.5 h-21 block relative z-2 max-w-full overflow-clip aspect-[auto_722/84] align-middle max-md:w-[9.0625rem] max-md:h-[1.0625rem] md:max-lg:w-123.5 md:max-lg:h-[3.5625rem]" data-ditto-id="style-br-2" data-component="image" alt={"Two panel image: (1) a stickman looking at a mirror in front of the reader reading this app (reader is represented as a happy pink alien saying \"I <3 this site\"), saying \"Golly! Who is this swaggy critter?\". Second panel is the same stickman's face up very close saying \"Oh hi! ^-^ It's just you\"."} height="84" src="/assets/cloned/images/47c87a724211.png" width="722" />
                        </a>
                        <p className="box-content block relative z-3 mt-[0.1875rem] text-[0.5rem] leading-2.5">
                          <strong className="box-content inline font-bold" data-ditto-id="style-div">
                            {"© Arija A. <"}
                            <a className="box-content inline underline cursor-pointer" data-ditto-id="style-link-3" data-component="link" href="https://ad.ari.lt/ads/contact?for=23bhRo40hCqwNIJ42a5lYc5QprnbHwgD-M6QnSsSafxAwA" rel="noopener noreferrer nofollow">
                              contact
                            </a>
                            {"> under CC BY-NC-SA 4.0 | "}
                            <a className="box-content inline underline cursor-pointer" data-ditto-id="style-image-12" data-component="link" href="https://ad.ari.lt/" rel="noopener noreferrer">
                              Arivertisements
                            </a>
                          </strong>
                        </p>
                        {" "}
                      </div>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
                {" "}
              </center>
              {" "}
              <hr className="w-206.5 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-[9.0625rem] md:max-lg:w-123.5" data-ditto-id="style-br-4" />
              {" "}
              <h3 className="block max-w-175 mx-auto text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-button" data-component="heading">
                Shrines
              </h3>
              {" "}
              <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-air-3-7-2026-6-34-12">
                {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
              </ul>
              {" "}
              <h3 className="block max-w-175 mx-auto text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-31" data-component="heading">
                Pages
              </h3>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-component="heading">
                {"Reading & writing"}
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-button-3">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-8" data-component="link" href="https://hex.ooo/library/library_of_babel.html" target="_blank">
                  Library of Babel
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-figure" data-component="link" href="https://www.threadings.io/youve-been-traumatized-into-hating/" target="_blank">
                  You've been traumatized into hating reading
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-image-7" data-component="link" href="https://aresluna.org/the-hardest-working-font-in-manhattan/" target="_blank">
                  The hardest working font in Manhattan
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-figcaption" data-component="link" href="https://thenewinquiry.com/book-of-lamentations/" target="_blank">
                  Book of Lamentations
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-link-16" data-component="heading">
                Statistics
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-ul-11" data-component="link" href="https://esci.thenewstatistics.com/esci-dances.html" target="_blank">
                  ESCI statistics simulation
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-component="heading">
                Ecology
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-link-12">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-p-5" data-component="link" href="https://mascontext.com/issues/surveillance/abbott-h-thayers-vanishing-ducks-surveillance-art-and-camouflage/" target="_blank">
                  Surveillence, art and camouflage
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-span" data-component="heading">
                Art
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-link-17">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-image" data-component="link" href="https://www.lovelifedrawing.com/how-to-simplify-values/" target="_blank">
                  How to simplify values
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-18" data-component="link" href="https://gurneyjourney.blogspot.com/2008/05/color-zones-of-face.html" target="_blank">
                  Colour zones of the face
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-image-2" data-component="heading">
                Political
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-aside-2">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-navbar" data-component="link" href="https://www.prochoiceactionnetwork-canada.org/articles/anti-tales.shtml" target="_blank">
                  When the Anti-Choice Choose
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-nav-2" data-component="heading">
                Spiritual
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-heading-20">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-6" data-component="link" href="https://www.ijstr.org/final-print/nov2017/Vastu-Shastra-And-Feng-Shui-The-Ancient-Sciences-And-Their-Fusion-In-Context-Of-Indian-Architecture.pdf/" target="_blank">
                  Vastu Shastra and Feng Shui
                </a>
                {" "}
              </p>
              {" "}
              <hr className="w-206.5 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-[9.0625rem] md:max-lg:w-123.5" data-ditto-id="style-p-11" />
              {" "}
              <h3 className="block max-w-175 mx-auto text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-19" data-component="heading">
                Websites
              </h3>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-18" data-component="heading">
                Art
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-ul-6">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-li-4" data-component="link" href="http://kawayoo.net/" target="_blank">
                  Kawayoo [non-HTTPS]
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-20" data-component="link" href="https://www.yasmeenabedifard.net/" target="_blank">
                  Yasmeen Abedifard
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-li-5" data-component="link" href="https://www.svetlin.gr/" target="_blank">
                  Svetlin Vassilev
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-21" data-component="link" href="https://danhays.org/index.html" target="_blank">
                  Dan Hays
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-7" data-component="link" href="https://prassio.net/" target="_blank">
                  Prassio
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-11" data-component="link" href="https://line-of-action.com/en" target="_blank">
                  Line of Action
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-ul-7" data-component="link" href="https://paint.toys/" target="_blank">
                  Paint Toys
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-component="heading">
                Ecology
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto" data-ditto-id="style-p-3">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-32" data-component="link" href="https://allesoverpaddenstoelen.nl/" target="_blank">
                  Alles over paddenstoelen
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-4" data-component="heading">
                Reading
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-5" data-component="link" href="https://wuthering-heights.co.uk/wh/index/" target="_blank">
                  Wuthering Heights reader's guide
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-8" data-component="link" href="https://libraryofbabel.info/" target="_blank">
                  Library of Babel
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-12" data-component="link" href="https://hex.ooo/library/" target="_blank">
                  Hex's Library
                </a>
                {" "}
              </p>
              {" "}
              <h4 className="border border-outset border-accent block max-w-175 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-ul-8" data-component="heading">
                Webmastery
              </h4>
              {" "}
              <p className="block max-w-175 mb-4 mx-auto">
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-22" data-component="link" href="https://internetphonebook.net/" target="_blank">
                  The Internet Phonebook
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-li-6" data-component="link" href="https://thoughts.melonking.net/guides/introduction-to-the-web-revival-1-what-is-the-web-revival/" target="_blank">
                  Web Revival guide
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-23" data-component="link" href="https://www.w3schools.com/" target="_blank">
                  W3Schools
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-9" data-component="link" href="https://matthewjamestaylor.com/custom-tags/" target="_blank">
                  Custom HTML tags
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-13" data-component="link" href="https://sadgrlonline.github.io/html-cheatsheet/" target="_blank">
                  HTML Cheatsheet
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-ul-9" data-component="link" href="https://goblin-heart.net/sadgrl/learn/articles/beginners-guide-neocities/" target="_blank">
                  Neocities beginners guide
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-33" data-component="link" href="https://sadgrl.online/guides/" target="_blank">
                  Coding guides
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-24" data-component="link" href="https://www.freeformatter.com/html-formatter.html" target="_blank">
                  HTML formatter
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-34" data-component="link" href="https://htmlcommentbox.com/" target="_blank">
                  Comment box
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-25" data-component="link" href="https://www.cbox.ws/" target="_blank">
                  CBox
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-10" data-component="link" href="https://atabook.org/" target="_blank">
                  Atabook
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-6" data-component="link" href="https://pixel-me.tokyo/" target="_blank">
                  Pixelfyer
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-hr-11" data-component="link" href="https://css-ig.net/pinga/" target="_blank">
                  Pinga image optimizer
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-14" data-component="link" href="https://www.photopea.com/" target="_blank">
                  Photopea
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-ul-10" data-component="link" href="https://www.birme.net/" target="_blank">
                  Bulk image resizer
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-li-7" data-component="link" href="https://app.dithermark.com/" target="_blank">
                  Dithermark
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-26" data-component="link" href="https://gifcities.org/" target="_blank">
                  GifCities
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-li-8" data-component="link" href="http://textfiles.com/underconstruction/" target="_blank">
                  'Under Construction'
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-27" data-component="link" href="https://www.pixelcut.ai/uncrop/" target="_blank">
                  {"AI Uncrop & Expand"}
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-image-8" data-component="link" href="https://www.rw-designer.com/cursor-library/" target="_blank">
                  Cursor library
                </a>
                {" "}
              </p>
              {" "}
              <div className="block">
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-span-3" data-component="link" href="https://artwork.neocities.org/" target="_blank">
                  {" "}
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-component="image" alt="Artwork Neocities" src="/assets/cloned/images/44f872e0d8ec.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-footer-3" data-component="link" href="https://pixelsafari.neocities.org/" target="_blank">
                  {" "}
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-image-6" data-component="image" alt="Pixel Safari" src="/assets/cloned/images/6716c356b811.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-br" data-component="link" href="https://capstasher.neocities.org/88x31collection-page1.html" target="_blank">
                  {" "}
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-28" data-component="image" alt="Capstasher 88x31 collection" src="/assets/cloned/images/7cff9d08737d.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-13" data-component="link" href="https://99gifshop.neocities.org/" target="_blank">
                  {" "}
                  <img className="w-22 h-[1.9375rem] inline-block max-w-full m-0.5 rounded-xs overflow-clip align-top [font-family:'Source_Code_Pro']" data-ditto-id="style-link-14" data-component="image" alt="99gifshop" src="/assets/cloned/images/2a18a7808223.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-10" data-component="link" href="https://cameronsworld.net/" target="_blank">
                  <div className="h-[1.9375rem] border border-outset border-color-004 inline-block m-0.5 p-1 rounded-xs align-top [font-family:'Source_Code_Pro'] text-[0.6875rem] leading-3.5 bg-accent cursor-default" data-ditto-id="style-br-3" data-component="button" alt="cameronsworld">
                    Camerons world
                  </div>
                </a>
                {" "}
              </div>
              {" "}
              <hr className="w-206.5 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-[9.0625rem] md:max-lg:w-123.5" data-ditto-id="style-lastupdate" />
              {" "}
              <div className="block">
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-ditto-id="style-link-15" data-component="image" alt="" src="/assets/cloned/images/cd9603834381.gif" />
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-11" data-component="link" href="https://anlucas.neocities.org/GifFiles" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="anlucas website" src="/assets/cloned/images/c5a2ecb88777.gif" />
                </a>
                {" "}
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/3a1319ebcfcb.gif" />
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-38" data-component="link" href="https://visce.neocities.org/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="visce website" src="/assets/cloned/images/a4f00e4b13e6.gif" />
                </a>
                {" "}
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/5aa3728751c5.gif" />
                {" "}
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/24206eacb994.gif" />
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-39" data-component="link" href="https://anlucas.neocities.org/GifFiles" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="anlucas website" src="/assets/cloned/images/7e240622a37f.gif" />
                </a>
                {" "}
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/29a7af45c9de.gif" />
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-40" data-component="link" href="https://sixey.es/" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="sixey.es website" src="/assets/cloned/images/68c9b724e005.png" />
                </a>
                {" "}
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/265e438a3e5d.gif" />
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-41" data-component="link" href="https://www.mabsland.com/Adoption.html" target="_blank">
                  <img className="w-[5.5625rem] h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="mabsland website" height="31px" src="/assets/cloned/images/bae515b3260c.gif" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-42" data-component="link" href="https://debtdeath.neocities.org/buttons" target="_blank">
                  <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip" data-component="image" alt="" src="/assets/cloned/images/0683a6f5f042.png" />
                </a>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0">
            <div className="block" id="navbar">
              <nav className="block" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <p className="block max-w-175 mb-4">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-43" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-44" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-45" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-46" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-47" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-48" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-49" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-50" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-35" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-36" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" />
            {"Last updated: "}
            <span className="inline" id="lastupdate" />
            {" "}
            <div className="block py-2.5">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-37" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
