import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/library/reading-log", label: "Anime Log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Mental Notes" }
];
const ListRow2_data = [
    { href: "/info/about/", label: "About" },
];
const ListRow_cids: string[][] = [
    ["n27", "n28"],
    ["n29", "n30"],
    ["n31", "n32"]
];
const ListRow2_cids: string[][] = [
    ["n43", "n44"],
    ["n45", "n46"],
    ["n47", "n48"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4" data-cid="n1">
        <div className="block" data-cid="n2" id="header">
          <header className="block my-5 text-center" data-cid="n3">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-cid="n4" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between" data-cid="n5">
          <main className="border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0" data-cid="n6">
            <section className="block text-center" data-cid="n7">
              <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-cid="n8" data-component="heading">
                Page not found
              </h2>
              {" "}
              <p className="block mb-4" data-cid="n9">
                {"This page doesn't exist, has been moved, or is under construction. At least these hamsters finally have an audience! :) "}
              </p>
              {" "}
              <img className="w-[10.1875rem] h-41 inline max-w-full overflow-clip max-md:w-32.5 max-md:h-[8.1875rem]" data-cid="n10" data-component="image" alt="hamsters playing in a band" src="/assets/cloned/images/ced4ef033936.gif" />
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-cid="n11">
            <div className="h-full block" data-cid="n12" id="navbar">
              <nav className="block" data-cid="n13" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-cid="n14" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n15" />
                {" "}
                <p className="block mb-4" data-cid="n16">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n17" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n24" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n25" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n26">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n33" />
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n40" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n41" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n42">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n49" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n50" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n51">
                  <li className="list-item" data-cid="n52">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n53" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-cid="n56" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-cid="n57">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-cid="n58">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" data-cid="n59" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-cid="n60">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-cid="n61" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-cid="n62" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n63" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n64" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n65" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-cid="n66" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-cid="n67" />
            {"Last updated: "}
            <span className="inline" data-cid="n68" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-cid="n69">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n70" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-cid="n71" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
