import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow2_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["style-image-4", "style-br-5"],
    ["style-link-11", "style-link"],
    ["style-link-2", "style-image-5"]
];
const ListRow2_meta: string[][] = [
    ["style-link-30", "style-p-4"],
    ["style-button-2", "style-june-2-7-2026-16-20-47"],
    ["style-heading-19", "style-span-2"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="w-full border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <section className="block">
              <div className="block">
                <h4 className="border border-outset border-accent block max-w-125 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] text-center bg-surface-2" data-ditto-id="style-p-2" data-component="heading">
                  Narcissus
                </h4>
                {" "}
                <article className="w-115 flex mb-8 mx-auto pt-1 pb-[1.0625rem] px-7.5 bg-surface max-md:-mr-[9.9375rem] max-md:ml-0" data-ditto-id="style-image-3">
                  <div className="w-25 h-12.5 block align-top bg-clr-9 after:content-['Green'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-aside" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-color-004 after:content-['YellowGreen'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-navbar-2" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-10 after:content-['#FFF394'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-nav" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-11 after:content-['#F5B027'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-heading-15" />
                  {" "}
                </article>
                {" "}
                <h4 className="border border-outset border-accent block max-w-125 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] text-center bg-surface-2" data-component="heading">
                  Winter
                </h4>
                {" "}
                <article className="w-115 flex mb-8 mx-auto pt-1 pb-[1.0625rem] px-7.5 bg-surface max-md:-mr-[9.9375rem] max-md:ml-0" data-ditto-id="style-p-6">
                  <div className="w-25 h-12.5 block align-top bg-clr-12 after:content-['#38471f'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-link-4" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-13 after:content-['#7aa300'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-heading-16" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-14 after:content-['#cce7ff'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-ul" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-surface-4 after:content-['WhiteSmoke'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-li-9" />
                  {" "}
                </article>
                {" "}
                <h4 className="border border-outset border-accent block max-w-125 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] text-center bg-surface-2" data-ditto-id="style-link-5" data-component="heading">
                  Swan
                </h4>
                {" "}
                <article className="w-115 flex mb-8 mx-auto pt-1 pb-[1.0625rem] px-7.5 bg-surface max-md:-mr-[9.9375rem] max-md:ml-0" data-ditto-id="style-li-3">
                  <div className="w-25 h-12.5 block align-top bg-foreground after:content-['#DarkSlateGray'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-link-6" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-15 after:content-['#LemonChiffon'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-hr" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-color-005 after:content-['#LightSteelBlue'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-heading-9" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-16 after:content-['#GhostWhite'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-ul-2" />
                  {" "}
                </article>
                {" "}
                <h4 className="border border-outset border-accent block max-w-125 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] text-center bg-surface-2" data-component="heading">
                  Orchid
                </h4>
                {" "}
                <article className="w-115 flex mb-8 mx-auto pt-1 pb-[1.0625rem] px-7.5 bg-surface max-md:-mr-[9.9375rem] max-md:ml-0" data-ditto-id="style-heading">
                  <div className="w-25 h-12.5 block align-top bg-clr-17 after:content-['#Teal'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-18 after:content-['#Orchid'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-heading-2" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-19 after:content-['#Pink'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-ul-12" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-background after:content-['#OldLace'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-li" />
                  {" "}
                </article>
                {" "}
                <h4 className="border border-outset border-accent block max-w-125 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] text-center bg-surface-2" data-ditto-id="style-hr-2" data-component="heading">
                  Cherry
                </h4>
                {" "}
                <article className="w-115 flex mb-8 mx-auto pt-1 pb-[1.0625rem] px-7.5 bg-surface max-md:-mr-[9.9375rem] max-md:ml-0" data-ditto-id="style-heading-17">
                  <div className="w-25 h-12.5 block align-top bg-primary after:content-['#ForestGreen'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-ul-3" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-20 after:content-['#Crimson'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-li-10" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-21 after:content-['#Violet'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-link-7" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-22 after:content-['#MistyRose'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-li-11" />
                  {" "}
                </article>
                {" "}
                <h4 className="border border-outset border-accent block max-w-125 mx-auto p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] text-center bg-surface-2" data-ditto-id="style-link-8" data-component="heading">
                  Garden
                </h4>
                {" "}
                <article className="w-115 flex mb-8 mx-auto pt-1 pb-[1.0625rem] px-7.5 bg-surface max-md:-mr-[9.9375rem] max-md:ml-0" data-ditto-id="style-hr-3">
                  <div className="w-25 h-12.5 block align-top bg-color-003 after:content-['#SeaGreen'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-heading-21" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-color-001 after:content-['#DarkSeaGreen'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-ul-4" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-23 after:content-['#Gold'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-link-29" />
                  {" "}
                  <div className="w-25 h-12.5 block align-top bg-clr-24 after:content-['#PapayaWhip'] after:block after:w-25 after:h-[0.8125rem] after:mt-12.5 after:text-clr-7 after:text-[0.6875rem] after:leading-[0.8125rem] after:text-center" data-ditto-id="style-p" />
                  {" "}
                </article>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-ditto-id="style-hr-5">
            <div className="h-full block" data-ditto-id="style-heading-3" id="navbar">
              <nav className="block" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-li-2" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-4" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-heading-7">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-5" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-li-12" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-9">
                  <li className="list-item" data-ditto-id="style-li-13">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-10" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-image-9">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-center" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-span-4" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-footer-2" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-footer">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-br-2" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-div">
                  <li className="list-item" data-ditto-id="style-link-3">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-12" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-br-4">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-button" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-air-3-7-2026-6-34-12" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-heading-10">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-link-31" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-button-3">
                  <li className="list-item" data-ditto-id="style-heading-8">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-figure" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-image-7">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-figcaption" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-link-16" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-ul-11">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      <div className="block" id="footer">
        <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-link-12">
          <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[23.1875rem] max-md:h-[1.1875rem]" data-ditto-id="style-p-5" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
          <br className="inline" data-ditto-id="style-span" />
          {" © 2023 Myrtletribe ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-17" data-component="link" href="/info/about">
            Sitemap
          </a>
          {" ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-image" data-component="link" href="https://neocities.org/site/myrtletribe">
            Neocities
          </a>
          {" ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-18" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
            {" "}
            <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-ditto-id="style-image-2" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
          </a>
          {" "}
          <br className="inline" data-ditto-id="style-aside-2" />
          {"Last updated: "}
          <span className="inline" data-ditto-id="style-navbar" id="lastupdate" />
          {" "}
          <div className="block py-2.5" data-ditto-id="style-nav-2">
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-20" data-component="link" href="https://brainmade.org/" target="_blank">
              {" "}
              <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-ditto-id="style-hr-6" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
            </a>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
      {" "}
    </>
  );
}
