import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow2_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["style-li-12", "style-link-9"],
    ["style-li-13", "style-link-10"],
    ["style-image-9", "style-center"]
];
const ListRow2_meta: string[][] = [
    ["n68", "style-div"],
    ["style-link-3", "style-image-12"],
    ["style-br-4", "style-button"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="w-full border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-component="heading">
              Car for cow
            </h2>
            {" "}
            <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-component="heading">
              02 july 2026
            </h4>
            {" "}
            <p className="block mb-4" data-ditto-id="style-p-2">
              <img className="w-96 h-72 inline max-w-full overflow-clip max-md:w-[7.5625rem] max-md:h-[5.6875rem]" data-ditto-id="style-image-3" data-component="image" alt="yellow toy car in windowsill" src="/assets/cloned/images/f0ad2537654e.png" />
              {" "}
            </p>
            {" "}
            <p className="block mb-4" data-ditto-id="style-aside">
              I have some plants outside my door, just like my neighbours. I moved here half a year ago and fell in love with how green the street was.
            </p>
            {" In one of them I put a little cow garden figurine. One day when I came home it was gone, made me super sad. I know it's a possibility that things will get taken or destroyed since they are in public. But you hope people will just not touch what they know isn't theirs.."}
            <p className="block mb-4" data-ditto-id="style-navbar-2" />
            {" "}
            <p className="block mb-4" data-ditto-id="style-nav">
              {"Yesterday I came home in the evening and there was a yellow blob in my lavender plant. It was this yellow toy car. Okay, it was not in the same plant as the cow, but could this be a peace offering? Anyway, I took it as an apology. It's missing wheels and one door, but yellow is my favourite colour. So it's now in my window sill, and I hope my cow is happy wherever it is. "}
            </p>
            {" "}
            <hr className="w-206.5 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-[7.5625rem] md:max-lg:w-123.5" data-ditto-id="style-heading-15" />
            {" "}
            <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
              Archive
            </h3>
            {" "}
            <details className="block" data-ditto-id="style-p-6">
              <summary className="list-item list-inside cursor-grabbing" data-ditto-id="style-link-4">
                Same hat (phone)
              </summary>
              {" "}
              <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-16" data-component="heading">
                19 may 2026
              </h4>
              {" "}
              <p className="block mb-4" data-ditto-id="style-ul">
                <img className="w-117 h-[21.9375rem] inline max-w-full overflow-clip max-md:w-[7.5625rem] max-md:h-[5.6875rem]" data-ditto-id="style-li-9" data-component="image" alt="holding jelly star" src="/assets/cloned/images/815ffb0137d7.png" />
                {" "}
              </p>
              {" "}
              <p className="block mb-4" data-ditto-id="style-link-5">
                You can imagine my surprise when last saturday, a customer pulled out her Jelly Star for me to scan her customer card. WHAT! SAME PHONE! I think I audibly gasped. We fangirled over the Jelly Star for a couple of minutes, it basically made my day.
              </p>
              {" "}
              <p className="block mb-4" data-ditto-id="style-li-3">
                Up here is mine, it's a little over a year old and works like a charm, it was the push I needed to delete all my social media accounts, it's a conversation starter and it wasn't even that expensive. But most importantly it's super frigging cute and I didn't think I could ever love a phone this much. MUAH!
              </p>
              {" "}
            </details>
            {" "}
            <details className="block" data-ditto-id="style-link-6">
              <summary className="list-item list-inside cursor-grabbing" data-ditto-id="style-hr">
                Wasp in my house
              </summary>
              {" "}
              <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-9" data-component="heading">
                05 may 2026
              </h4>
              {" "}
              <p className="block mb-4" data-ditto-id="style-ul-2">
                <img className="w-117 h-[21.9375rem] inline max-w-full overflow-clip max-md:w-[7.5625rem] max-md:h-[5.6875rem]" data-component="image" alt="wasp in glass photo from above" src="/assets/cloned/images/9d85fbc1b6d1.png" />
              </p>
              {" "}
              <p className="block mb-4" data-ditto-id="style-heading">
                I picked up some packages from online and when I was inside I heard a slightly alarming scratching sound. I thought it was the cardboard settling at first, but when I looked there was a wasp on it just, trying to dig I think. I'm not super scared of wasps so I put it in a glass to free it but it didn't want to fly so I thought it's probably hungry, thirsty or both (it hadn't rained for a month here).
              </p>
              {" "}
              <p className="block mb-4">
                {"So I put a piece of apple and a cap with water in it and it started eating, yay! It only started to fly again after half an hour or so, and I let it out. It didn't sting me! Maybe that's good luck :) "}
              </p>
              {" "}
            </details>
            {" "}
            <details className="block" data-ditto-id="style-heading-2">
              <summary className="list-item list-inside cursor-grabbing" data-ditto-id="style-ul-12">
                Lucky leather shoe
              </summary>
              {" "}
              <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-li" data-component="heading">
                25 april 2026
              </h4>
              {" "}
              <p className="block mb-4" data-ditto-id="style-hr-2">
                <img className="w-132 h-[21.8125rem] inline max-w-full overflow-clip max-md:w-[7.5625rem] max-md:h-20 md:max-lg:w-123.5 md:max-lg:h-[20.4375rem]" data-ditto-id="style-heading-17" data-component="image" alt="small yellow leather slipper" src="/assets/cloned/images/1ed0bcfa5c06.png" />
              </p>
              {" "}
              <p className="block mb-4" data-ditto-id="style-ul-3">
                During my fieldwork I found this small, yellow leather shoe (?). It said 'Miguel' on the sole in nice calligraphy letters. I thought it was a babyshoe at first, but it was way too small for that. But it seemed very elaborate for a doll? It felt like a lucky shoe, but I didn't want to take it because of the name, I assume that is the owner so maybe they will come back for it.. So we put it on the bench. I would actually love a pair of these in my size, lol.
              </p>
              {" "}
            </details>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-ditto-id="style-li-10">
            <div className="block" data-ditto-id="style-link-7" id="navbar">
              <nav className="block" data-ditto-id="style-li-11" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-link-8" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-3" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-heading-21">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-4" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-29" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-p">
                  <li className="list-item" data-ditto-id="style-hr-5">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-3" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-2" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-4" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-7" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-5">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-span-4" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-footer-2" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-footer">
                  <li className="list-item" data-ditto-id="style-image-4">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-br-5" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-link-11">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-link-2" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-image-5" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-br-2">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-air-3-7-2026-6-34-12" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-heading-10">
                  <li className="list-item" data-ditto-id="style-link-30">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-p-4" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-button-2">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-june-2-7-2026-16-20-47" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-heading-19" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-ditto-id="style-span-2">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-link-31">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-button-3">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-ditto-id="style-heading-8" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-ditto-id="style-figure" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-7" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-figcaption" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-16" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-ditto-id="style-ul-11" />
            {"Last updated: "}
            <span className="inline" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-ditto-id="style-link-12">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-p-5" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-ditto-id="style-span" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
