import MediaTile from "./components/media-tile";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const MediaTile_data = [
    { alt: "naruto fanart of pain", imgSrc: "/assets/cloned/images/97e1afb4ba14.jpg", text: "Pain (Naruto), dec [fanart]" },
    { alt: "mouthwashing fanart of jimmy", imgSrc: "/assets/cloned/images/8eb64865b2de.jpg", text: "Jimmy (Mouthwashing), dec [fanart]" },
    { alt: "elfenlied fanart of lucy", imgSrc: "/assets/cloned/images/54a5892bd3d8.jpg", text: "Lucy, nov [fanart]" },
    { alt: "original art of an elf with white hair", imgSrc: "/assets/cloned/images/4cf7cbfd5a11.jpg", text: "November, nov [original]" },
    { alt: "steins;gate fanart of faris and rintaro", imgSrc: "/assets/cloned/images/ff1cfa9231f8.jpg", text: "Faris/Rintaro, oct [fanart]" },
    { alt: "elfenlied fanart of lucy", imgSrc: "/assets/cloned/images/3dcd7f10fe28.jpg", text: "Lucy elfen lied, april [fanart]" },
    { alt: "graffiti style drawing of elf", imgSrc: "/assets/cloned/images/fa2553b73022.jpg", text: "Graffiti, jan [original]" },
    { alt: "avatar fanart of toph", imgSrc: "/assets/cloned/images/6de22e3b11b6.jpg", text: "Toph, jan [fanart]" },
    { alt: "lain fanart of lain", imgSrc: "/assets/cloned/images/aeacff3a5d3c.jpg", text: "Serial experiments lain, jan [fanart]" }
];
const MediaTile_data2 = [
    { alt: "evangelion fanart of rei as a chibi", imgSrc: "/assets/cloned/images/d0cd5073be78.jpg", text: "Chibi rei, july [fanart]" },
    { alt: "evangelion fanart of asuka sitting", imgSrc: "/assets/cloned/images/9440dbb5f86a.jpg", text: "Asuka sitting, april [fanart]" },
    { alt: "evangelion fanart of asuka looking over shoulder", imgSrc: "/assets/cloned/images/35012d56c9b7.jpg", text: "Asuka, march [fanart]" },
    { alt: "original art of red demon girl", imgSrc: "/assets/cloned/images/018664a32d28.jpg", text: "Red demon Palla, feb [original]" }
];
const MediaTile_data3 = [
    { alt: "evangelion fanart of asuka", imgSrc: "/assets/cloned/images/883c2d9c3df0.jpg", text: "Asuka, sept [fanart]" },
    { alt: "original art of a cave bug girl", imgSrc: "/assets/cloned/images/580af9eba6d1.jpg", text: "Cave bug, aug [original]" },
    { alt: "avatar fanart of katara", imgSrc: "/assets/cloned/images/0db2d86bdb1a.jpg", text: "Katara waterbending, july [fanart]" }
];
const ListRow_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow2_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const MediaTile_meta: string[][] = [
    ["n29", "style-heading-2", "style-ul-12"],
    ["style-li", "style-hr-2", "style-heading-17"],
    ["style-ul-3", "style-li-10", "style-link-7"],
    ["style-li-11", "style-link-8", "style-hr-3"],
    ["style-heading-21", "style-ul-4", "style-link-29"],
    ["style-p", "style-hr-5", "style-heading-3"],
    ["n47", "style-li-2", "style-hr-4"],
    ["style-heading-7", "style-ul-5", "style-li-12"],
    ["style-link-9", "style-li-13", "style-link-10"]
];
const MediaTile_meta2: string[][] = [
    ["style-link", "style-link-2", "style-image-5"],
    ["style-br-2", "n68", "style-div"],
    ["style-link-3", "style-image-12", "style-br-4"],
    ["style-button", "style-air-3-7-2026-6-34-12", "n75"]
];
const MediaTile_meta3: string[][] = [
    ["style-link-30", "style-p-4", "style-button-2"],
    ["style-june-2-7-2026-16-20-47", "style-heading-19", "style-span-2"],
    ["style-link-31", "n84", "style-button-3"]
];
const ListRow_meta: string[][] = [
    ["n117", "style-p-3"],
    ["style-link-32", "style-heading-4"],
    ["n121", "style-heading-5"]
];
const ListRow2_meta: string[][] = [
    ["style-link-33", "style-link-24"],
    ["style-link-34", "style-link-25"],
    ["style-hr-10", "style-heading-6"]
];
const MediaTile_styles = [
    { className: "h-61 max-md:h-39.5 md:max-lg:h-36" },
    { className: "h-71.5 max-md:h-46 md:max-lg:h-42" },
    { className: "h-[16.9375rem] max-md:h-[10.9375rem] md:max-lg:h-[9.9375rem]" },
    { className: "h-60.5 max-md:h-39 md:max-lg:h-35.5" },
    { className: "h-81.5 max-md:h-52.5 md:max-lg:h-48" },
    { className: "h-42.5 max-md:h-27.5 md:max-lg:h-25" },
    { className: "h-[19.5625rem] max-md:h-50.5 md:max-lg:h-46" },
    { className: "h-[15.6875rem] max-md:h-40.5 md:max-lg:h-[9.1875rem]" },
    { className: "h-[19.8125rem] max-md:h-51 md:max-lg:h-46.5" }
];
const MediaTile_styles2 = [
    { className: "h-[21.5625rem] max-md:h-55.5 md:max-lg:h-[12.6875rem]" },
    { className: "h-[20.9375rem] max-md:h-54 md:max-lg:h-[12.3125rem]" },
    { className: "h-85.5 max-md:h-55 md:max-lg:h-[12.5625rem]" },
    { className: "h-[17.0625rem] max-md:h-44 md:max-lg:h-[10.0625rem]" }
];
const MediaTile_styles3 = [
    { className: "h-[20.0625rem] max-md:h-[12.9375rem] md:max-lg:h-[11.8125rem]" },
    { className: "h-71 max-md:h-[11.4375rem] md:max-lg:h-[10.4375rem]" },
    { className: "h-80.5 max-md:h-52 md:max-lg:h-[11.8125rem]" }
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-background [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <section className="h-full block text-center">
              <p className="block mb-4">
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-p-2" data-component="link" href="#illustrations">
                  #illustrations
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-3" data-component="link" href="#roughwork">
                  #roughwork
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-aside" data-component="link" href="#scraps">
                  #scraps
                </a>
                <br className="inline" data-ditto-id="style-navbar-2" />
                {" "}
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:text-center" data-ditto-id="style-nav">
                  may contain (suggestive) nudity
                </span>
                {" "}
              </p>
              {" "}
              <article className="block mb-4 max-md:overflow-x-hidden max-md:overflow-y-auto" data-ditto-id="style-heading-15" id="illustrations">
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                  Illustrations
                </h3>
                {" "}
                <div className="grid gap-2.5 grid-cols-3 max-md:gap-5 max-md:grid-cols-1" data-ditto-id="style-p-6">
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-link-4" data-component="heading">
                    2026
                  </h4>
                  {" "}
                  <figure className="block mb-4 max-md:mb-0" data-ditto-id="style-heading-16">
                    <img className="w-60.5 h-71.5 block max-w-full mx-[0.8375rem] rounded-xs overflow-clip max-md:w-39 max-md:h-46 max-md:max-w-100 max-md:mx-0 md:max-lg:w-35.5 md:max-lg:h-42 md:max-lg:mx-2" data-ditto-id="style-ul" data-component="image" alt="original art girl with philodendron" src="/assets/cloned/images/a7e23734c6e4.jpg" />
                    {" "}
                    <figcaption className="block mt-2" data-ditto-id="style-li-9">
                      Philodendron, march [original]
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-link-5" data-component="heading">
                    2025
                  </h4>
                  {" "}
                  <figure className="block mb-4 max-md:mb-0" data-ditto-id="style-li-3">
                    <img className="w-60.5 h-[16.3125rem] block max-w-full mx-[0.8375rem] rounded-xs overflow-clip max-md:w-39 max-md:h-[10.5625rem] max-md:max-w-100 max-md:mx-0 md:max-lg:w-35.5 md:max-lg:h-38.5 md:max-lg:mx-2" data-ditto-id="style-link-6" data-component="image" alt="Fanart Takopi" src="/assets/cloned/images/835de46ba457.jpg" />
                    {" "}
                    <figcaption className="block mt-2" data-ditto-id="style-hr">
                      Takopi's original sin, july [fanart]
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <figure className="block mb-4 max-md:mb-0" data-ditto-id="style-heading-9">
                    <img className="w-60.5 h-71.5 block max-w-full mx-[0.8375rem] rounded-xs overflow-clip max-md:w-39 max-md:h-46 max-md:max-w-100 max-md:mx-0 md:max-lg:w-35.5 md:max-lg:h-42 md:max-lg:mx-2" data-ditto-id="style-ul-2" data-component="image" alt="Fanart Dexter" src="/assets/cloned/images/34ad963315e5.jpg" />
                    {" "}
                    <figcaption className="block mt-2">
                      Dexter, jan [fanart]
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading" data-component="heading">
                    2024
                  </h4>
                  {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
                  {" "}
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-image-9" data-component="heading">
                    2023
                  </h4>
                  {" "}
                  <figure className="block mb-4 max-md:mb-0" data-ditto-id="style-center">
                    <img className="w-60.5 h-[24.3125rem] block max-w-full mx-[0.8375rem] rounded-xs overflow-clip max-md:w-39 max-md:h-[15.6875rem] max-md:max-w-100 max-md:mx-0 md:max-lg:w-35.5 md:max-lg:h-[14.3125rem] md:max-lg:mx-2" data-ditto-id="style-span-4" data-component="image" alt="original art of a human form mushroom spirit with long green hair" src="/assets/cloned/images/eff75489bd4b.jpg" />
                    {" "}
                    <figcaption className="block mt-2" data-ditto-id="style-footer-2">
                      Mushroom spirit, dec [original]
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <figure className="block mb-4 max-md:mb-0" data-ditto-id="style-footer">
                    <img className="w-60.5 h-[20.8125rem] block max-w-full mx-[0.8375rem] rounded-xs overflow-clip max-md:w-39 max-md:h-[13.4375rem] max-md:max-w-100 max-md:mx-0 md:max-lg:w-35.5 md:max-lg:h-49 md:max-lg:mx-2" data-ditto-id="style-image-4" data-component="image" alt="legend of zelda fanart of zelda" src="/assets/cloned/images/53399ed3495e.jpg" />
                    {" "}
                    <figcaption className="block mt-2" data-ditto-id="style-br-5">
                      Zelda, may [fanart]
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-link-11" data-component="heading">
                    2021
                  </h4>
                  {MediaTile_data2.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles2[i]} />)}
                  {" "}
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-10" data-component="heading">
                    2020
                  </h4>
                  {MediaTile_data3.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles3[i]} />)}
                  {" "}
                  <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] col-span-full text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading-8" data-component="heading">
                    2019
                  </h4>
                  {" "}
                  <figure className="block mb-4 max-md:mb-0" data-ditto-id="style-figure">
                    <img className="w-60.5 h-[18.6875rem] block max-w-full mx-[0.8375rem] rounded-xs overflow-clip max-md:w-39 max-md:h-[12.0625rem] max-md:max-w-100 max-md:mx-0 md:max-lg:w-35.5 md:max-lg:h-44 md:max-lg:mx-2" data-ditto-id="style-image-7" data-component="image" alt="mushishi fanart of renzu" src="/assets/cloned/images/846627825cd8.jpg" />
                    {" "}
                    <figcaption className="block mt-2" data-ditto-id="style-figcaption">
                      Renzu, apr [fanart]
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                </div>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-16" data-component="link" href="#illustrations">
                  ⤴️ back to top
                </a>
                {" "}
              </article>
              {" "}
              <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
                My art elsewhere
              </h3>
              {" "}
              <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-11">
                <li className="list-item before:content-['❧_'] before:inline-block before:w-[0.6625rem] before:h-[1.1rem] before:mr-1.5 before:text-foreground before:text-lg before:leading-[1.125rem] before:text-center">
                  <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-12" data-component="link" href="https://myrtletribe.tumblr.com/">
                    Tumblr
                  </a>
                </li>
              </ul>
              {" "}
              <p className="block mb-4" data-ditto-id="style-p-5">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:text-center" data-ditto-id="style-span">
                  All artwork © 2009 by Myrtletribe is licensed under CC BY-NC-ND 4.0
                </span>
                {" "}
              </p>
              {" "}
              <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-17" data-component="link" href="https://creativecommons.org/licenses/by-nc-nd/4.0" target="_blank">
                <img className="w-22 h-[1.9375rem] inline max-w-full overflow-clip [cursor:alias]" data-ditto-id="style-image" data-component="image" alt="creative commons license website" src="/assets/cloned/images/213cd6c2bb0b.png" />
              </a>
              {" "}
              <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-18" data-component="link" href="https://notbyai.fyi/" target="_blank">
                <img className="w-[6.0625rem] h-[1.9375rem] inline max-w-full overflow-clip [cursor:alias]" data-ditto-id="style-image-2" data-component="image" alt="notbyAI website" height="31px" src="/assets/cloned/images/b821b1122b41.png" />
              </a>
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-ditto-id="style-aside-2">
            <div className="block" data-ditto-id="style-navbar" id="navbar">
              <nav className="block" data-ditto-id="style-nav-2" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-heading-20" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-6" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-p-11">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-19" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-18" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-6">
                  <li className="list-item" data-ditto-id="style-li-4">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-20" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-li-5">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-21" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-7" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-11" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-7">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-8" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-12" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-8">
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-22" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-li-6">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-23" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-9" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-13" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-9">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-11" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-14" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-10">
                  <li className="list-item" data-ditto-id="style-li-7">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-26" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-li-8">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-27" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-image-8" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-span-3">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      <div className="block" id="footer">
        <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-footer-3">
          <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[23.1875rem] max-md:h-[1.1875rem]" data-ditto-id="style-image-6" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
          <br className="inline" data-ditto-id="style-br" />
          {" © 2023 Myrtletribe ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-28" data-component="link" href="/info/about">
            Sitemap
          </a>
          {" ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-13" data-component="link" href="https://neocities.org/site/myrtletribe">
            Neocities
          </a>
          {" ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-14" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
            {" "}
            <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-ditto-id="style-image-10" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
          </a>
          {" "}
          <br className="inline" data-ditto-id="style-br-3" />
          {"Last updated: "}
          <span className="inline" data-ditto-id="style-lastupdate" id="lastupdate" />
          {" "}
          <div className="block py-2.5">
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-15" data-component="link" href="https://brainmade.org/" target="_blank">
              {" "}
              <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-ditto-id="style-image-11" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
            </a>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
      {" "}
    </>
  );
}
