import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
import { blogEntries } from "./content";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { text: "06/09 - ", href: "#potluck-2026", label: "Lemon and Raisin Cake" },
    { text: "04/08 - ", href: "#hardlife", label: "Life was tough today" },
    { text: "30/06 - ", href: "#project2026", label: "Isopod project and Norway" },
    { text: "02/04 - ", href: "#kingfisher2026", label: "Common Kingfisher" },
    { text: "March - ", href: "#pyramid2026", label: "Levelled up in Maslow's pyramid" },
    { text: "10/03 - ", href: "#lightsteelblue2026", label: "Interview with Ms. LightSteelBlue" }
];
const ListRow_data2 = [
    { text: "November - ", href: "#nov2025", label: "Life resumed! Genomics kinda boring..." },
    { text: "October - ", href: "#oct2025", label: "Concussion, life paused" },
    { text: "September - ", href: "#sept2025", label: "Ecology and evolution" },
    { text: "August - ", href: "#aug2025", label: "Summertime jam making" }
];
const ListRow2_data = [
    { href: "/library/reading-log", label: "Anime Log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Mental Notes" }
];
const ListRow3_data = [
    { href: "/info/about/", label: "About" },
];
const ListRow_cids: string[][] = [
    ["n30", "n31"],
    ["n32", "n33"],
    ["n34", "n35"],
    ["n36", "n37"],
    ["n38", "n39"],
    ["n40", "n41"]
];
const ListRow_cids2: string[][] = [
    ["n51", "n52"],
    ["n53", "n54"],
    ["n55", "n56"],
    ["n57", "n58"]
];
const ListRow2_cids: string[][] = [
    ["n75", "n76"],
    ["n77", "n78"],
    ["n79", "n80"]
];
const ListRow3_cids: string[][] = [
    ["n91", "n92"],
    ["n93", "n94"],
    ["n95", "n96"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4" data-cid="n1">
        <div className="block" data-cid="n2" id="header">
          <header className="block my-5 text-center" data-cid="n3">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-cid="n4" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between" data-cid="n5">
          <main className="w-full border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0" data-cid="n6">
            {blogEntries.map((entry) => (
              <article className="block mb-4" id={entry.id} key={entry.id}>
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-component="heading">{entry.title}</h2>
                <time className="block text-clr-8 italic">{entry.date}</time>
                <p className="block mb-4 text-justify">{entry.body}</p>
              </article>
            ))}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-cid="n59">
            <div className="block" data-cid="n60" id="navbar">
              <nav className="block" data-cid="n61" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-cid="n62" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n63" />
                {" "}
                <p className="block mb-4" data-cid="n64">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n65" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n72" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n73" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n74">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n81" />
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n88" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n89" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n90">
                  {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n97" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n98" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n99">
                  <li className="list-item" data-cid="n100">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n101" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-cid="n104" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-cid="n105">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-cid="n106">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" data-cid="n107" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-cid="n108">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-cid="n109" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-cid="n110" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n111" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n112" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n113" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-cid="n114" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-cid="n115" />
            {"Last updated: "}
            <span className="inline" data-cid="n116" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-cid="n117">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n118" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-cid="n119" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
