import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import ListRow3 from "./components/list-row3";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { text: "06/09 - ", href: "#potluck-2026", label: "Lemon and Raisin Cake" },
    { text: "04/08 - ", href: "#hardlife", label: "Life was tough today" },
    { text: "30/06 - ", href: "#project2026", label: "Isopod project and Norway" },
    { text: "02/04 - ", href: "#kingfisher2026", label: "Common Kingfisher" },
    { text: "March - ", href: "#pyramid2026", label: "Levelled up in Maslow's pyramid" },
    { text: "10/03 - ", href: "#lightsteelblue2026", label: "Interview with Ms. LightSteelBlue" }
];
const ListRow_data2 = [
    { text: "November - ", href: "#nov2025", label: "Life resumed! Genomics kinda boring..." },
    { text: "October - ", href: "#oct2025", label: "Concussion, life paused" },
    { text: "September - ", href: "#sept2025", label: "Ecology and evolution" },
    { text: "August - ", href: "#aug2025", label: "Summertime jam making" }
];
const ListRow2_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow3_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["style-heading-2", "style-ul-12"],
    ["style-li", "style-hr-2"],
    ["style-heading-17", "style-ul-3"],
    ["style-li-10", "style-link-7"],
    ["style-li-11", "style-link-8"],
    ["style-hr-3", "style-heading-21"]
];
const ListRow_meta2: string[][] = [
    ["style-ul-5", "style-li-12"],
    ["style-link-9", "style-li-13"],
    ["style-link-10", "style-image-9"],
    ["style-center", "style-span-4"]
];
const ListRow2_meta: string[][] = [
    ["n75", "style-heading-10"],
    ["style-link-30", "style-p-4"],
    ["style-button-2", "style-june-2-7-2026-16-20-47"]
];
const ListRow3_meta: string[][] = [
    ["n91", "style-ul-11"],
    ["n93", "style-link-12"],
    ["style-p-5", "style-span"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="w-full border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0">
            <article className="block mb-4" id="potluck-2026">
              <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-component="heading">
                Lemon and Raisin Cake
              </h2>
              {" "}
              <h3 className="flex mt-[11.5px] mb-1.5 items-center text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-p-2" data-component="heading">
                <time className="flex ml-155.5 items-center text-clr-8 italic leading-[1.1875rem] max-md:ml-0 md:max-lg:ml-72.5" data-ditto-id="style-image-3">
                  06 september 2026
                </time>
              </h3>
              {" "}
              <p className="block mb-4 text-justify" data-ditto-id="style-aside">
                {"This year I was honoured to co-host the "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-navbar-2" data-component="link" href="https://skep.place/events/potluck/2026/event">
                  Small Web Potluck 2026
                </a>
                {" together with "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-nav" data-component="link" href="https://skep.place/">
                  Skep
                </a>
                {", and due to "}
                <s className="inline line-through" data-ditto-id="style-heading-15">
                  both of our blogs being yellow
                </s>
                {" yellow simply being the best colour, we added 'yellow' as a theme. Joke was on me, because I couldn't think of anything yellow to make for the entire month that was fun enough to me for the event. But then it so happened that I was able to get an oven and suddenly I had a many more options, so I went with something I think almost everyone likes: lemon cake! "}
              </p>
              {" "}
              <p className="block mb-4 text-justify">
                <img className="w-135 h-[25.3125rem] inline max-w-full overflow-clip max-md:w-35 max-md:h-[6.5625rem] md:max-lg:w-123.5 md:max-lg:h-[23.1875rem]" data-ditto-id="style-p-6" data-component="image" alt="lemon cake on white table and blue plate with cut lemon" src="/assets/cloned/images/2cf726b89e96.png" />
              </p>
              {" "}
              <p className="block mb-4 text-justify" data-ditto-id="style-link-4">
                {"I used a lemon cake recipe from "}
                <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-heading-16" data-component="link" href="https://uitpaulineskeuken.nl/recept/citroencake-met-kwark">
                  Pauline's Keuken
                </a>
                . It's in Dutch, but browsers should be able to translate it. Eventually I will add the recipe to my recipes page, but that is still under construction hehe..
              </p>
              {" "}
              <p className="block mb-4 text-justify" data-ditto-id="style-ul">
                {"Couple of things to note: it's actually a lemon and poppy seed cake, but I couldn't find poppy seed, so I used yellow raisins instead (because why not), and I actually really like the combination. I also had to use four eggs instead of 3 because mine were small. You can adjust the portion size on the site and the ingredients adjust automatically, which is really nice. I will definitely be making this again! It turned out really well, not too sweet. I might use more lemon zest next time. Thank you everyone for joining this delightful event! "}
              </p>
              {" "}
              <p className="block mb-4 text-justify" data-ditto-id="style-li-9" />
              {" "}
            </article>
            {" "}
            <article className="hidden mb-4" data-ditto-id="style-link-5" id="project2026">
              <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-li-3">
                Isopod project and Norway
              </h2>
              {" "}
              <p className="block mb-4 text-justify" data-ditto-id="style-link-6">
                It's been a hot minute since I made a blog post. Over the past months I finished my project on urban and rural isopod differences. When we started I was a little bit skeptical, ecological data can seem so... random at times, with huge spreads. So I was worried I didn't have large enough sample sizes to get results.. but we did have some really interesting results. One of those was that urban soil microhabitats are a lot drier than rural ones, even though they are similar in temperature. I think temperature must be more limiting for them than humidity.
              </p>
              {" "}
              <p className="block mb-4 text-justify" data-ditto-id="style-hr">
                {"I am now enjoying my summer vacation and looking forward to completing a couple of goals: "}
              </p>
              {" I am soo excited to finally have some time to work on these! I feel like I had to put a pause on everything I wanted to do for half a year... all in the name of science I guess. "}
              <p className="block mb-4 text-justify" data-ditto-id="style-heading-9">
                Speaking of science, for my final project I'm hoping to go to Norway. Studying polar bears was probably a bit too ambitious, as it is a very small and difficult field to get into. But studying anything related to snow honestly feels like a dream to me right now. Whether it's looking at respiration under the snow cover, or circadian rythms of small mammals in the winter.. anything related to polar ecology! I have to admit it feels scary to live in a different country for a couple of months. But probably SO WORTH IT! It helps that a study friend of mine is currently also doing her last project in Trondheim. There is hope for me still....
              </p>
              {" "}
            </article>
            {" "}
            <hr className="w-206.5 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35 md:max-lg:w-123.5" data-ditto-id="style-ul-2" />
            {" "}
            <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-component="heading">
              Archive
            </h3>
            {" "}
            <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-heading" data-component="heading">
              2026
            </h4>
            {" "}
            <ul className="block mb-4 [list-style-type:none] list-outside">
              {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
              <li className="list-item" data-ditto-id="style-ul-4">
                {"February - "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-29" data-component="link" href="#feb2026">
                  <em className="inline italic" data-ditto-id="style-p">
                    Oniscus asellus
                  </em>
                  {" doesn't have lungs?!"}
                </a>
              </li>
              <li className="list-item" data-ditto-id="style-hr-5">
                {"21/02 - "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-heading-3" data-component="link" href="#manifesto2026">
                  Using social media as art platforms
                </a>
              </li>
              <li className="list-item">
                {"January - "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-li-2" data-component="link" href="#jan2026">
                  Isopods research
                </a>
              </li>
            </ul>
            {" "}
            <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] text-sm leading-[0.8125rem] bg-surface-2" data-ditto-id="style-hr-4" data-component="heading">
              2025
            </h4>
            {" "}
            <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-heading-7">
              {ListRow_data2.map((d, i) => <ListRow key={i} d={d} />)}
            </ul>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-ditto-id="style-footer-2">
            <div className="block" data-ditto-id="style-footer" id="navbar">
              <nav className="block" data-ditto-id="style-image-4" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-br-5" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-link-11" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-link">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-2" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-image-5" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-br-2">
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-div" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-link-3">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-image-12" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-br-4" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-button" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-air-3-7-2026-6-34-12">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-heading-19" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-span-2" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-31">
                  <li className="list-item">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-button-3" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-heading-8">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-figure" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-image-7" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-figcaption" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-16">
                  {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-link-17" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-image" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-link-18">
                  <li className="list-item" data-ditto-id="style-image-2">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-aside-2" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-navbar">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-nav-2" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-heading-20" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-ditto-id="style-hr-6">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-p-11">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" data-ditto-id="style-link-19" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-heading-18">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-ditto-id="style-ul-6" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-ditto-id="style-li-4" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-20" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-li-5" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-link-21" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-ditto-id="style-hr-7" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-ditto-id="style-heading-11" />
            {"Last updated: "}
            <span className="inline" data-ditto-id="style-ul-7" id="lastupdate" />
            {" "}
            <div className="block py-2.5">
              <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-p-3" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-ditto-id="style-link-32" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
