import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/library/reading-log", label: "Anime Log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Mental Notes" }
];
const ListRow2_data = [
    { href: "/info/about/", label: "About" },
];
const ListRow_cids: string[][] = [
    ["n68", "n69"],
    ["n70", "n71"],
    ["n72", "n73"]
];
const ListRow2_cids: string[][] = [
    ["n84", "n85"],
    ["n86", "n87"],
    ["n88", "n89"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4" data-cid="n1">
        <div className="block" data-cid="n2" id="header">
          <header className="block my-5 text-center" data-cid="n3">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-cid="n4" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between" data-cid="n5">
          <main className="w-full border-r-2 border-solid border-r-border block pt-3 pb-5 px-5 bg-clr-0" data-cid="n6">
            <section className="block" data-cid="n7">
              <p className="block mb-4" data-cid="n8">
                Hi I'm Myrtletribe, I got that name from a random elf name generator when I was little. I was born in november 1993. I always loved the idea of having a personal site, so I built one to archive my art, and it snowballed from there. Thanks for visiting :)
              </p>
              {" "}
              <p className="block mb-4" data-cid="n9">
                {"Read my "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n10" data-component="link" href="/library/blog">
                  manifesto
                </a>
                {" on using social media as an art platform if you want to know why I deleted almost all my social media accounts."}
              </p>
              {" "}
              <div className="flex justify-between gap-8 max-lg:flex-col" data-cid="n11">
                <article className="w-full max-w-125 block mb-[0.8rem] pl-2.5 rounded-xs text-[0.8125rem] italic leading-4 bg-accent" data-cid="n12">
                  <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n13" data-component="heading">
                    ~Favourites~
                  </h3>
                  {" "}
                  <ul className="block mb-[0.8rem] [list-style-type:none] list-outside" data-cid="n14">
                    <li className="list-item" data-cid="n15">
                      <strong className="inline font-bold" data-cid="n16">
                        mammal
                      </strong>
                      : polarbear, orca, otter, weasel
                    </li>
                    <li className="list-item" data-cid="n17">
                      <strong className="inline font-bold" data-cid="n18">
                        bird
                      </strong>
                      : kingfisher, hop, owl
                    </li>
                    <li className="list-item" data-cid="n19">
                      <strong className="inline font-bold" data-cid="n20">
                        colour
                      </strong>
                      {": "}
                      <span className="inline text-surface bg-color-001" data-cid="n21">
                        green
                      </span>
                      {", "}
                      <span className="inline bg-clr-5" data-cid="n22">
                        yellow
                      </span>
                      {" "}
                    </li>
                    <li className="list-item" data-cid="n23">
                      <strong className="inline font-bold" data-cid="n24">
                        flower
                      </strong>
                      : daffodil, dandelion, orchid
                    </li>
                    <li className="list-item" data-cid="n25">
                      <strong className="inline font-bold" data-cid="n26">
                        music
                      </strong>
                      : Enya, Tame Impala, Super Mama Djombo, Joanna Newsom, Kraftwerk, Kate Bush, Gorillaz, Daft Punk, John Maus, Kerala Dust, Stranglers
                    </li>
                    <li className="list-item" data-cid="n27">
                      <strong className="inline font-bold" data-cid="n28">
                        moth
                      </strong>
                      : Kentish Glory (
                      <em className="inline" data-cid="n29">
                        Endromis versicolora
                      </em>
                      ), which I had the pleasure of finding on Schiermonnikoog and doing thermoregulation trials with. The colours and shape are simply perfection!
                    </li>
                  </ul>
                  {" "}
                </article>
                {" "}
                <img className="w-50 h-[12.8125rem] block max-w-full mb-[0.9375rem] rounded-sm self-start overflow-clip [filter:drop-shadow(var(--clr-2)_1px_2px_2px)] max-md:w-38.5 max-md:h-39.5" data-cid="n30" data-component="image" alt="kentish glory female" src="/assets/cloned/images/c28fee4d8b90.png" />
                {" "}
              </div>
              {" "}
              <article className="w-[32.5%] border-[3px] border-solid border-clr-6 block mb-[0.9rem] pt-3 pr-[0.3125rem] pl-4.5 text-sm leading-4.5 tracking-[2px] max-md:w-full md:max-lg:w-[54.5%]" data-cid="n31">
                <h4 className="border border-outset border-accent block mt-[2.9px] p-[0.1875rem] rounded-[1px] leading-[0.8125rem] bg-surface-2" data-cid="n32" data-component="heading">
                  Bucket list
                </h4>
                {" "}
                <ul className="block mb-[0.9rem] [list-style-type:none] list-outside" data-cid="n33">
                  <li className="list-item before:content-['❧_'] before:inline-block before:w-[0.7875rem] before:h-[1.1rem] before:mr-1.5 before:text-foreground before:text-lg before:leading-[1.125rem] before:tracking-[2px]" data-cid="n34">
                    Take sewing classes
                  </li>
                  <li className="list-item before:content-['❧_'] before:inline-block before:w-[0.7875rem] before:h-[1.1rem] before:mr-1.5 before:text-foreground before:text-lg before:leading-[1.125rem] before:tracking-[2px]" data-cid="n35">
                    <s className="inline line-through" data-cid="n36">
                      Paint kitchen yellow
                    </s>
                  </li>
                  <li className="list-item before:content-['❧_'] before:inline-block before:w-[0.7875rem] before:h-[1.1rem] before:mr-1.5 before:text-foreground before:text-lg before:leading-[1.125rem] before:tracking-[2px]" data-cid="n37">
                    Learn Linux
                  </li>
                  <li className="list-item before:content-['❧_'] before:inline-block before:w-[0.7875rem] before:h-[1.1rem] before:mr-1.5 before:text-foreground before:text-lg before:leading-[1.125rem] before:tracking-[2px]" data-cid="n38">
                    Polar research
                  </li>
                </ul>
                {" "}
              </article>
              {" "}
              <hr className="w-206.5 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-38.5 md:max-lg:w-123.5" data-cid="n39" />
              {" "}
              <div className="block" data-cid="n40">
                <img className="w-37.5 h-5 inline max-w-full overflow-clip" data-cid="n41" data-component="image" alt="" src="/assets/cloned/images/b4ef1f4f5906.gif" />
                {" "}
                <img className="w-37.5 h-5 inline max-w-full overflow-clip" data-cid="n42" data-component="image" alt="" src="/assets/cloned/images/81f893aca9be.gif" />
                {" "}
                <img className="w-37.5 h-5 inline max-w-full overflow-clip" data-cid="n43" data-component="image" alt="" src="/assets/cloned/images/d675861cb778.gif" />
                {" "}
                <img className="w-37.5 h-5 inline max-w-full overflow-clip" data-cid="n44" data-component="image" alt="" src="/assets/cloned/images/dbf10031207c.gif" />
                {" "}
              </div>
              {" "}
              <div className="block" data-cid="n45">
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n46" data-component="link" href="https://www.deviantart.com/drowsyfaun/art/--739746930" target="_blank">
                  <img className="w-[6.1875rem] h-14 inline max-w-full overflow-clip" data-cid="n47" data-component="image" alt="drowsyfaun deviantart" src="/assets/cloned/images/3fbd7f6ed564.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n48" data-component="link" href="https://vampyre.neocities.org/pixls" target="_blank">
                  <img className="w-[6.1875rem] h-[3.4375rem] inline max-w-full overflow-clip" data-cid="n49" data-component="image" alt="vampyre website" src="/assets/cloned/images/891491743354.png" />
                </a>
                {" "}
                <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n50" data-component="link" href="https://blog.spacehey.com/entry?id=808983" target="_blank">
                  <img className="w-[6.1875rem] h-14 inline max-w-full overflow-clip" data-cid="n51" data-component="image" alt="spacehey blog" src="/assets/cloned/images/488d56d83c41.png" />
                </a>
                {" "}
              </div>
              {" "}
            </section>
            {" "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-clr-0" data-cid="n52">
            <div className="block" data-cid="n53" id="navbar">
              <nav className="block" data-cid="n54" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-cid="n55" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n56" />
                {" "}
                <p className="block mb-4" data-cid="n57">
                  <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n58" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n65" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n66" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n67">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n74" />
                {" "}
                
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n81" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n82" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n83">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-cid="n90" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-color-001 text-[1.1875rem] leading-[1.6875rem]" data-cid="n91" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-cid="n92">
                  <li className="list-item" data-cid="n93">
                    <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n94" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-cid="n97" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-cid="n98">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-cid="n99">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      <div className="block" data-cid="n100" id="footer">
        <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-cid="n101">
          <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[23.1875rem] max-md:h-[1.1875rem]" data-cid="n102" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
          <br className="inline" data-cid="n103" />
          {" © 2023 Myrtletribe ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] cursor-grabbing" data-cid="n104" data-component="link" href="/info/about">
            Sitemap
          </a>
          {" ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n105" data-component="link" href="https://neocities.org/site/myrtletribe">
            Neocities
          </a>
          {" ❧ "}
          <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n106" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
            {" "}
            <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-cid="n107" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
          </a>
          {" "}
          <br className="inline" data-cid="n108" />
          {"Last updated: "}
          <span className="inline" data-cid="n109" id="lastupdate" />
          {" "}
          <div className="block py-2.5" data-cid="n110">
            <a className="inline text-primary underline [text-decoration-style:dotted] [cursor:alias]" data-cid="n111" data-component="link" href="https://brainmade.org/" target="_blank">
              {" "}
              <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-cid="n112" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
            </a>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
      {" "}
    </>
  );
}
