import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const ListRow_data = [
    { href: "/library/reading-log", label: "Reading log" },
    { href: "/library/blog", label: "Blog" },
    { href: "/library/snapshots", label: "Snapshots" }
];
const ListRow2_data = [
    { label: "About" },
    { label: "Site" },
    { label: "Archive" }
];
const ListRow_meta: string[][] = [
    ["style-link-6", "style-hr"],
    ["style-heading-9", "style-ul-2"],
    ["n27", "style-heading"]
];
const ListRow2_meta: string[][] = [
    ["style-link-8", "style-hr-3"],
    ["style-heading-21", "style-ul-4"],
    ["style-link-29", "style-p"]
];

export default function Page() {
  return (
    <>
      <div className="block max-w-275 mx-auto px-4">
        <div className="block" id="header">
          <header className="block my-5 text-center">
            <h1 className="block mb-2.5 text-color-003 [font-family:'CS_Roastery_Pixel',_monospace] text-[4rem] font-thin leading-[4.1875rem] transform-[matrix(1.18,0,0,1,0,0)] origin-[534px_33.5px] max-md:origin-[171.5px_33.5px] md:max-lg:origin-[368px_33.5px]" data-component="heading">
              {" Myrtletribe "}
            </h1>
            {" "}
          </header>
          {" "}
        </div>
        {" "}
        <div className="flex justify-between">
          <main className="w-full border-2 border-solid border-border block pt-3 pb-5 px-5 bg-surface-4">
            {" photos here lol "}
          </main>
          {" "}
          <aside className="w-full block max-w-50 pt-3 pb-5 px-5 text-right bg-surface-4">
            <div className="h-full block" id="navbar">
              <nav className="block" data-ditto-id="style-p-2" data-component="nav">
                <h2 className="block mb-2.5 text-color-003 text-2xl leading-[2.125rem]" data-ditto-id="style-image-3" data-component="heading">
                  Navigation
                </h2>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-aside" />
                {" "}
                <p className="block mb-4" data-ditto-id="style-navbar-2">
                  <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-nav" data-component="link" href="/">
                    HOMEPAGE
                  </a>
                </p>
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-15" data-component="heading">
                  [Gallery]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  <li className="list-item" data-ditto-id="style-p-6">
                    <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-link-4" data-component="link" href="/gallery/artwork">
                      Artwork
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-heading-16">
                    <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul" data-component="link" href="/gallery/photography">
                      Photography
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-li-9" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-5" data-component="heading">
                  [Library]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-li-3">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-2" data-component="heading">
                  [Scrapbook]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-ul-12">
                  <li className="list-item" data-ditto-id="style-li">
                    <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-hr-2" data-component="link" href="/scrapbook/palettes">
                      Palettes
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-heading-17">
                    <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-3" data-component="link" href="https://myrtletribe.neocities.org/scrapbook/recipes/">
                      Recipes
                    </a>
                  </li>
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-li-10" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-link-7" data-component="heading">
                  [Info]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside" data-ditto-id="style-li-11">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} />)}
                </ul>
                {" "}
                <hr className="w-40 h-[0.1875rem] border-t-[3px] border-dotted border-t-border block my-4 overflow-hidden text-muted-foreground max-md:w-35" data-ditto-id="style-hr-5" />
                {" "}
                <h3 className="block mb-[0.3125rem] text-[1.1875rem] leading-[1.6875rem]" data-ditto-id="style-heading-3" data-component="heading">
                  [Guest]
                </h3>
                {" "}
                <ul className="block mb-4 [list-style-type:none] list-outside">
                  <li className="list-item" data-ditto-id="style-li-2">
                    <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-hr-4" data-component="link" href="/guest/guestbook">
                      Guestbook
                    </a>
                  </li>
                  <li className="list-item" data-ditto-id="style-heading-7">
                    <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-ul-5" data-component="link" href="/guest/links">
                      Links
                    </a>
                  </li>
                </ul>
                {" "}
              </nav>
              {" "}
              <img className="w-40 h-32 inline max-w-full overflow-clip max-md:w-35 max-md:h-28" data-ditto-id="style-li-12" data-component="image" alt="minecraft polar bear" src="/assets/cloned/images/418c897b29cf.png" />
              {" "}
              <center className="block [text-align:-webkit-center]" data-ditto-id="style-link-9">
                <span className="inline text-muted-foreground text-[0.8125rem] italic leading-4 before:content-['✽'] before:text-muted-foreground before:text-[0.8125rem] before:leading-4 before:[text-align:-webkit-center]" data-ditto-id="style-li-13">
                  Sidebear
                </span>
              </center>
              {" "}
            </div>
            {" "}
          </aside>
          {" "}
        </div>
        {" "}
        <div className="block" data-ditto-id="style-link-10" id="footer">
          <footer className="block max-w-200 my-[1.35rem] mx-auto p-0.5 text-sm leading-4.5 text-center" data-ditto-id="style-image-9">
            <img className="w-135.5 h-7 inline max-w-full overflow-clip max-md:w-[21.1875rem] max-md:h-4.5" data-ditto-id="style-center" data-component="image" alt="" src="/assets/cloned/images/f3d7e7eebe8f.png" />
            <br className="inline" data-ditto-id="style-span-4" />
            {" © 2023 Myrtletribe ❧ "}
            <a className="inline text-color-005 underline [text-decoration-style:dotted] cursor-grabbing" data-ditto-id="style-footer-2" data-component="link" href="/info/about">
              Sitemap
            </a>
            {" ❧ "}
            <a className="inline text-color-005 underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-footer" data-component="link" href="https://neocities.org/site/myrtletribe">
              Neocities
            </a>
            {" ❧ "}
            <a className="inline text-color-005 underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-image-4" data-component="link" href={"https://clap.fc2.com/post/myrtletribe/?url=https%3A%2F%2Fmyrtletribe.neocities.org&title=myrtletribe"} target="_blank" title="Web Clap by FC2">
              {" "}
              <img className="w-20 h-4.5 inline max-w-full overflow-clip align-middle [filter:sepia(0.9)]" data-ditto-id="style-br-5" data-component="image" alt="Web Clap by FC2" src="/assets/cloned/images/dc4483310132.gif" />
            </a>
            {" "}
            <br className="inline" data-ditto-id="style-link-11" />
            {"Last updated: "}
            <span className="inline" data-ditto-id="style-link" id="lastupdate" />
            {" "}
            <div className="block py-2.5" data-ditto-id="style-link-2">
              <a className="inline text-color-005 underline [text-decoration-style:dotted] [cursor:alias]" data-ditto-id="style-image-5" data-component="link" href="https://brainmade.org/" target="_blank">
                {" "}
                <img className="w-24 h-7.5 inline max-w-full overflow-clip [filter:drop-shadow(var(--clr-4)_0px_0px_10px)]" data-ditto-id="style-br-2" data-component="image" alt="brainmade website" src="/assets/cloned/svg/ac6a469d4655.svg" />
              </a>
              {" "}
            </div>
            {" "}
          </footer>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
    </>
  );
}
